global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: prometheus
    metrics_path:
      /api/v1/nodes/kind-control-plane/proxy/metrics/cadvisor
    static_configs:
      - targets: ['localhost:8001']
